package com.autoadda.apis.part.util;

public enum Status {
	REQUESTED, CONFIRMED, REJECTED, BLOCKED, DELETED, INACTIVE, ACTIVE, PENDING_VERIFICATION, VERIFIED, SUSPENDED,
	CLOSED, ARCHIVED, ON_HOLD, EXPIRED, PENDING_ACTIVATION, ACTIVATED, DEACTIVATED, PENDING_REVIEW, WORK_INPROGRESS,
	PENDING_INVOICE, READY_FOR_DELIVERY, DELIVERED, DONE, ASSIGNED, WAITING_FOR_SPARES, INPROGRESS, JOB_COMPLETED,
	DELIVERED_TO_CUSTOMER, WAITING_FOR_PAYMENT, PAYMENT_RECEIVED, CANCELLED, REFUNDED, PENDING_REFUND, REFUND_INITIATED,
	REFUND_COMPLETED, PENDING_APPROVAL, APPROVED, REJECTED_BY_ADMIN, PENDING_SHIPMENT, SHIPPED, DELIVERED_TO_WAREHOUSE,
	ALL, COMPLETED, INVOICED, PENDING_PAYMENT, PAYMENT_FAILED, PAYMENT_PENDING, PAYMENT_SUCCESSFUL, PAYMENT_CANCELLED,
	NEW, SCHEDULED, INVOICE_INITIATED, CREATED, PENDING, LISTED, SOLD, REMOVED
}
